services:
  - type: web
    name: material-hardness-predictor
    env: python
    plan: starter
    region: oregon

    runtime: python-3.10.13   # â† REQUIRED OR RENDER USES PYTHON 3.13!!!

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: >
      gunicorn "src.app.app:create_app()"
      --bind 0.0.0.0:$PORT
      --workers 2
      --timeout 120

    autoDeploy: true
