services:
  - type: web
    name: material-hardness-predictor
    env: python
    plan: starter
    region: oregon
    buildCommand: "pip install -r requirements.txt && make train || true"
    startCommand: "gunicorn src.app.app:create_app()"
    repo: "TheComputationalCore/material-hardness-oxidation-prediction"
    branch: main
